### ISSUE TITLE
Benchmark dataset

### ISSUE THREAD

**Issue by wxslby** [pbehjatii/DiVANet#3]
Hello，could you share the benchmark dataset again, the link to colab  can't be opened.  Thanks!

**Comment by pbehjatii** [comment]
You also can download the benchmark datasets from the link above:
https://drive.google.com/drive/folders/1B3DJGQKB6eNdwuQIhdskA64qUuVKLZ9u
https://drive.google.com/drive/folders/1xyiuTr6ga6ni-yfTP7kyPHRmfBakWovo
